### ISSUE TITLE
是否可以控制输出结果只显示error而不显示warn

### ISSUE THREAD

**Issue by hhhyaaon** [MarxJiao/VScode-fecs#1]
![image](https://cloud.githubusercontent.com/assets/17123400/25034517/a5d8ab6c-2119-11e7-8e39-d1635813b09c.png)
输出如图，是否有配置项可以只过滤显示error 信息？

**Comment by MarxJiao** [comment]
可以考虑加个配置，周末看下

**Comment by MarxJiao** [comment]
#2 添加了检查level的配置，已发布0.8.1版本的插件。
