### ISSUE TITLE
可以支持在每行前面添加圆点提示吗？

### ISSUE THREAD

**Issue by l5oo00** [MarxJiao/VScode-fecs#4]
如题， 就像下图这样：

![image](https://cloud.githubusercontent.com/assets/1233234/26160771/b750ea8a-3b54-11e7-8f3b-e07924fcd0b3.png)

哪行有问题， 就在那一行前面加个小圆点， 然后鼠标定位到那一行后， 在底部状态栏显示提示信息。

**Comment by MarxJiao** [comment]
暂时不支持
