### ISSUE TITLE
.jsx文件貌似不能执行check

### ISSUE THREAD

**Issue by zhangjunah** [MarxJiao/VScode-fecs#6]
.jsx文件在vscode中被认为是 Javascript React， languageId貌似不是jsx吧，所以应该是这个原因导致对.jsx文件不能执行fecs检查

![image](https://cloud.githubusercontent.com/assets/1746154/26353190/bf091ef4-3ff1-11e7-95d6-ae88d46c4051.png)

**Comment by MarxJiao** [comment]
我这里装了一个jsx插件把.jsx文件的languageId搞成jsx了，默认的.jsx文件的languageId是javascriptreact。0.9.1已修复
