### ISSUE TITLE
文件保存时自动检查的问题

### ISSUE THREAD

**Issue by zhangjunah** [MarxJiao/VScode-fecs#8]
开启了fecs.auto为true，打开vscode，在没有手动执行 cmd + shift + r 之前，无论如何修改文件并保存都不会自动执行fecs检查。 但是如果手动执行了一次cmd + shift + r之后，保存文件确实会自动执行fecs检查。  是否是插件的代码bug？还是vscode就不支持？

**Comment by MarxJiao** [comment]
vscode的插件是懒加载的，只有触发插件的命令后才会执行插件里的代码，这个保存执行fecs功能是在插件代码中写的，执行一次后才会初始化监听保存动作。这个问题暂时没找到比较好的解决方案。
